version: '3.8'

services:
  maintenance-page:
    image: nginx:alpine
    container_name: maintenance_mode
    ports:
      - "3000:80" # Takes over Gitea's port
      - "3001:80" # Takes over Grafana's port
    volumes:
      - ./maintenance_html:/usr/share/nginx/html:ro
